## Environment variables outside image context. These will be available until the first FROM statement.
ARG BASE_REGISTRY=registry1.dso.mil
ARG BASE_DEPLOY_IMAGE=ironbank/redhat/openjdk/openjdk17
ARG BASE_DEPLOY_TAG=1.17

####################################################################################################

## Base deploy image
FROM ${BASE_REGISTRY}/${BASE_DEPLOY_IMAGE}:${BASE_DEPLOY_TAG} AS deploy_container

USER root

# Upgrade first
RUN dnf -y upgrade --nodocs \
    && dnf clean all \
    && rm -rf /var/cache/dnf

COPY tak/security/*.rpm .
# Install EPEL 8 repo
RUN rpm -Uvh epel-release-latest-8.noarch.rpm

# Install dependencies
RUN dnf update -y --disableplugin=subscription-manager --nodocs \
    && dnf install -y --disableplugin=subscription-manager --nodocs \
           openssl \
           vim \
    && dnf clean all \
    && rm -rf /var/cache/dnf

# Harden java.security for FIPS compliance
RUN set -euxo pipefail && \
  JAVA_SECURITY_FILE="/usr/lib/jvm/java-17-openjdk/conf/security/java.security" && \
  cp "$JAVA_SECURITY_FILE" "${JAVA_SECURITY_FILE}.bak" && \
  sed -i '/jdk.certpath.disabledAlgorithms=/d' "$JAVA_SECURITY_FILE" && \
  sed -i '/jdk.tls.disabledAlgorithms=/d' "$JAVA_SECURITY_FILE" && \
  echo "" >> "$JAVA_SECURITY_FILE" && \
  echo "# FIPS hardening - disable weak algorithms" >> "$JAVA_SECURITY_FILE" && \
  echo "jdk.certpath.disabledAlgorithms=MD2, MD5, SHA1, DSA, RSA keySize < 2048" >> "$JAVA_SECURITY_FILE" && \
  echo "jdk.tls.disabledAlgorithms=SSLv3, RC4, MD5, SHA1, DH keySize < 2048, RSA keySize < 2048, DSA keySize < 2048" >> "$JAVA_SECURITY_FILE" && \
  echo "securerandom.source=file:/dev/urandom" >> "$JAVA_SECURITY_FILE" && \
  echo "security.useSystemPropertiesFile=false" >> "$JAVA_SECURITY_FILE"

# Set environment variable to enforce FIPS properties
ENV JAVA_TOOL_OPTIONS="-Dcom.redhat.fips=true -Djava.security.properties=/usr/lib/jvm/java-17-openjdk/conf/security/java.security"

#fix fips related issue, takserver needs the non fips providers so simply set them as fips providers so that they are available
RUN echo "fips.provider.1=SUN" >> $JAVA_HOME/conf/security/java.security
RUN echo "fips.provider.2=SunRsaSign" >> $JAVA_HOME/conf/security/java.security
RUN echo "fips.provider.3=SunEC" >> $JAVA_HOME/conf/security/java.security
RUN echo "fips.provider.4=SunJSSE" >> $JAVA_HOME/conf/security/java.security
RUN echo "fips.provider.5=SunJCE" >> $JAVA_HOME/conf/security/java.security
RUN echo "fips.provider.6=SunJGSS" >> $JAVA_HOME/conf/security/java.security
RUN echo "fips.provider.7=SunSASL" >> $JAVA_HOME/conf/security/java.security
RUN echo "fips.provider.8=XMLDSig" >> $JAVA_HOME/conf/security/java.security
RUN echo "fips.provider.9=SunPCSC" >> $JAVA_HOME/conf/security/java.security
RUN echo "fips.provider.10=JdkLDAP" >> $JAVA_HOME/conf/security/java.security
RUN echo "fips.provider.11=JdkSASL" >> $JAVA_HOME/conf/security/java.security
RUN echo "fips.provider.12=SunPKCS11" >> $JAVA_HOME/conf/security/java.security

RUN useradd -g 0 -u 1001 tak \
    && usermod -a -G root tak
USER tak:0

ARG ARG_CA_NAME
ENV CA_NAME=$ARG_CA_NAME
ARG ARG_STATE
ENV STATE=$ARG_STATE
ARG ARG_CITY
ENV CITY=$ARG_CITY
ARG ARG_ORGANIZATIONAL_UNIT
ENV ORGANIZATIONAL_UNIT=$ARG_ORGANIZATIONAL_UNIT
COPY --chown=tak:0 tak/certs/ /tak/certs
RUN chmod u=rwx /tak/certs \
          && chmod u=rw /tak/certs/*.* \
          && chmod u=rx /tak/certs/*.sh
WORKDIR /tak/certs/
ENTRYPOINT ["/tak/certs/generateClusterCertsIfNoneExist.sh"]
